# Ender's Game Configuration
debug: false
sql: sqlite
mysql:
    hostname: localhost
    port: '3306'
    database: EndersGame
    username: minecraft
    password: password
game:
    max-players: 24
    min-percent-to-start: 25
    percent-in-spawn-to-win: 20